# Generated by Django 4.1.6 on 2023-04-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
