# Generated by Django 4.1.6 on 2023-04-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
