# Generated by Django 4.1.6 on 2023-04-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.IntegerField()),
                ('LAST_EDIT', models.DateTimeField()),
            ],
        ),
    ]
