# Generated by Django 4.1.6 on 2023-06-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_plots_experiment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plots',
            old_name='RAW_PLOT',
            new_name='IS_RAW',
        ),
    ]
