# Generated by Django 4.1.6 on 2023-06-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_rename_raw_plot_plots_is_raw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='plots',
        ),
    ]
