# Generated by Django 4.1.6 on 2023-07-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_delete_plots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('PLOTS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IMG_FILE', models.BinaryField()),
                ('EXPERIMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.experiments')),
            ],
        ),
    ]
