# Generated by Django 4.1.6 on 2023-09-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_plots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('BLOCKS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('X_TRANS', models.CharField(max_length=255)),
                ('Y_TRANS', models.CharField(max_length=255)),
                ('L_X_LIM', models.FloatField()),
                ('R_X_LIM', models.FloatField()),
                ('L_Y_LIM', models.FloatField()),
                ('R_Y_LIM', models.FloatField()),
                ('FIT_TYPE', models.CharField(max_length=255)),
                ('X_TICK', models.FloatField()),
                ('Y_TICK', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='experiments',
            old_name='Experiment_ID',
            new_name='EXPERIMENT_ID',
        ),
        migrations.RenameField(
            model_name='experiments',
            old_name='Raw_DF',
            new_name='RAW_DF',
        ),
        migrations.DeleteModel(
            name='Plots',
        ),
        migrations.AddField(
            model_name='blocks',
            name='EXPERIMENTS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.experiments'),
        ),
    ]
