# Generated by Django 4.1.6 on 2023-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocks',
            name='X_TICK',
        ),
        migrations.RemoveField(
            model_name='blocks',
            name='Y_TICK',
        ),
        migrations.AddField(
            model_name='blocks',
            name='DEGREE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blocks',
            name='ER_MODE',
            field=models.CharField(default='range', max_length=255),
        ),
        migrations.AddField(
            model_name='blocks',
            name='PLOT',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blocks',
            name='X_MAJOR_TICK',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='blocks',
            name='X_MINOR_TICK',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='blocks',
            name='Y_MAJOR_TICK',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='blocks',
            name='Y_MINOR_TICK',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='FIT_TYPE',
            field=models.CharField(default='auto', max_length=255),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='L_X_LIM',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='L_Y_LIM',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='R_X_LIM',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='R_Y_LIM',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='X_TRANS',
            field=models.CharField(default='x', max_length=255),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='Y_TRANS',
            field=models.CharField(default='y', max_length=255),
        ),
    ]
