# Generated by Django 4.1.6 on 2023-09-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_remove_blocks_x_tick_remove_blocks_y_tick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='L_X_LIM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='L_Y_LIM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='R_X_LIM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='R_Y_LIM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='X_MAJOR_TICK',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='X_MINOR_TICK',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='Y_MAJOR_TICK',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='Y_MINOR_TICK',
            field=models.FloatField(default=None, null=True),
        ),
    ]
