# Generated by Django 4.1.6 on 2023-09-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_blocks_l_x_lim_alter_blocks_l_y_lim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocks',
            name='PLOT',
        ),
    ]
