# Generated by Django 4.2.7 on 2023-11-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_remove_blocks_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='DEGREE',
            field=models.FloatField(default=0),
        ),
    ]
