# Generated by Django 4.2.7 on 2023-11-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_blocks_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='X_ERR',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='Y_ERR',
            field=models.FloatField(null=True),
        ),
    ]
